# baseurl = ""  this is set at runtime in commandline
languageCode = "en-us"
title = "Code Coots"
# TODO set hugo's contentdir dynamically from code
contentdir = "../../../../content/hugo/pages"
[blackfriday]
  hrefTargetBlank = true
  plainIDAnchors = true
[params]
  site-description = "Blah Blah"
  site-creator= "Jim Shoe"
  sidebartitle="This is the Sidebar"
[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
  food-group = "food-groups"
