<!-- Any Javascripts required.  to be loaded in the head -->

<!-- Wired Dep and browserify  JS goes here -->

<script>
window.addEventListener('load', function() {
  var toggleButton = document.querySelector('#toggleButton');
  var collapsiblePanel = document.querySelector('#collapsiblePanel');
  toggleButton.addEventListener('click', function() {
    collapsiblePanel.toggle();
  });
});
</script>
