<include src="regions/head.phtml"></include>

<body class='page'>
     <include src="regions/header.phtml"></include>

    <div class="rollover-wrapper">

         <include src="regions/navbar.phtml"></include>
        <main>

         <include src="regions/sidebar.phtml"></include>

        <section id="content">

  <block name="article">This is where one melds in article content</block>

        </section>

          </main>
           <include src="regions/footer.phtml"></include>

       </div>

       <include src="components/javascripts.phtml"></include>

</body>
