<include src="regions/head.phtml"></include>

<body>

<include src="regions/header.phtml"></include>

<div class="rollover-wrapper">

<include src="regions/navbar.phtml"></include>

<main>

<include src="regions/sidebar-nav.phtml"></include>

<div class="content holy-grail__content">
      <block name="article">Base content for article here to be appended, prepended, replaced</block>
</div>

<include src="regions/sidebar-ads.phtml"></include>

</main>

    <!-- <footer class="holy-grail__footer">
        <include src="regions/footer.phtml"></include>
    </footer> -->

</div>

  <include src="components/javascripts.phtml"></include>

</body>
