<!-- Post load additional Javascript libraries at end of <body> tag  -->


<!-- custom js from your site assests -->
<script src="{{ BaseURL }}assets/bowerDeps.js"></script> <!-- any js code coming from bower using main key-->
<script src="{{ BaseURL }}assets/npmDeps.js"></script> <!-- any js code coming direct from npm (node_modules) using main key -->
<script src="{{ BaseURL }}assets/app.js"></script>  <!-- custom js site code using browserify and any required npm modules -->

<!-- TODO CDNs for production need to figure out how to automate this for use instead of bundled above -->
<!-- <script src='https://code.jquery.com/jquery-2.1.3.min.js'></script>
<script src='http://cdn.rawgit.com/garand/sticky/master/jquery.sticky.js'></script>
<script src="http://cdn.rawgit.com/f/loremjs/master/lorem.js"></script> -->
